// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0e6Aw9I_LUZTAKKXcY_Ck3UxSEvW_Is',
    appId: '1:1082370212254:web:ab50e05c529aa0519bd68f',
    messagingSenderId: '1082370212254',
    projectId: 'cgcalendar-2026',
    authDomain: 'cgcalendar-2026.firebaseapp.com',
    storageBucket: 'cgcalendar-2026.firebasestorage.app',
    measurementId: 'G-4JG4N3PM59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgSCD0KTUNhbnj3cBwwTFXqk3-RKRmck8',
    appId: '1:1082370212254:android:e7c16f834c70f9a99bd68f',
    messagingSenderId: '1082370212254',
    projectId: 'cgcalendar-2026',
    storageBucket: 'cgcalendar-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA0v4Tq5O80kI_9436_OSAg-TA0-QHHD4',
    appId: '1:1082370212254:ios:a10aa921831fd5529bd68f',
    messagingSenderId: '1082370212254',
    projectId: 'cgcalendar-2026',
    storageBucket: 'cgcalendar-2026.firebasestorage.app',
    androidClientId: '1082370212254-rb3a65kmgdbkvktpc92a9r7tbrak2eno.apps.googleusercontent.com',
    iosClientId: '1082370212254-hnsdhbv9mvakrlmb57cugr81hrfietdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cgCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA0v4Tq5O80kI_9436_OSAg-TA0-QHHD4',
    appId: '1:1082370212254:ios:a10aa921831fd5529bd68f',
    messagingSenderId: '1082370212254',
    projectId: 'cgcalendar-2026',
    storageBucket: 'cgcalendar-2026.firebasestorage.app',
    androidClientId: '1082370212254-rb3a65kmgdbkvktpc92a9r7tbrak2eno.apps.googleusercontent.com',
    iosClientId: '1082370212254-hnsdhbv9mvakrlmb57cugr81hrfietdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cgCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE0e6Aw9I_LUZTAKKXcY_Ck3UxSEvW_Is',
    appId: '1:1082370212254:web:24feb6773515f35b9bd68f',
    messagingSenderId: '1082370212254',
    projectId: 'cgcalendar-2026',
    authDomain: 'cgcalendar-2026.firebaseapp.com',
    storageBucket: 'cgcalendar-2026.firebasestorage.app',
    measurementId: 'G-LD6NN1X01L',
  );
}
